//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Work/Scripts/Player/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""CharacterControls"",
            ""id"": ""d4b0b025-f693-4395-b84f-ca4e1c346d88"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""4e4db10c-c177-4aff-86e9-7e61132d0bc1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""6e2997cb-0747-4a8e-9bf4-e7b3add23c39"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""089a6640-666e-4916-bb4c-52759ff652e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Defense"",
                    ""type"": ""Button"",
                    ""id"": ""5a5659e4-1baa-4c3f-9bc1-bb305e08e2ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveOnWall"",
                    ""type"": ""Value"",
                    ""id"": ""3fbd5894-0a3d-49f1-a52f-bf8d88bcbe7f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""JumpOnWall"",
                    ""type"": ""Button"",
                    ""id"": ""3b2932fc-605f-4045-a62f-7750454c190d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grapple"",
                    ""type"": ""Button"",
                    ""id"": ""ce78e4b5-9fa6-47fc-94e0-65b26046a9e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveOnGrapple"",
                    ""type"": ""Value"",
                    ""id"": ""ea98c9d0-813a-4ac8-a400-29abf0d5a944"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FirstSwordSkill"",
                    ""type"": ""Button"",
                    ""id"": ""85cbac00-c773-4a89-846d-e7354b65eb4b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondSwordSkill"",
                    ""type"": ""Button"",
                    ""id"": ""31e97701-e361-4a80-a37d-dbf02ee453eb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NormalSwordSkill"",
                    ""type"": ""Button"",
                    ""id"": ""599451d7-52ea-4450-bdec-63a167c9f050"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThirdSwordSkill"",
                    ""type"": ""Button"",
                    ""id"": ""260df730-5536-4891-9e5b-018623038c16"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwordBlock"",
                    ""type"": ""Button"",
                    ""id"": ""031b7bae-ba05-4957-b9a3-471f9bd4fc53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""fe82a7cd-1b44-4c30-a1ba-33880ce30d3e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d013116d-820d-4c40-9e79-ad7ae3a052ea"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a0b36748-d89d-4f96-be63-9c8d55c1630e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""92486393-a5de-48a6-bc5a-841e5898e42d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""07a74845-d4b7-4dea-85a7-082ad6545335"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e32be3f5-789f-401c-9fbe-200595fcd9ba"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe28fab4-0c21-4142-8185-f97e10c971b9"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff14655c-ad35-41a2-95c2-ffd4a31ce0b2"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Defense"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""1fd8c740-9680-4885-8c0c-cc4fbbe95937"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveOnWall"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a7e0c7c4-a487-4f84-bcc4-305d92f68d0f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveOnWall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0bed6460-eb4a-4ad5-8f69-5eca9037c249"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveOnWall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e4cbb290-f3f9-4b71-aa4a-463b89049c91"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveOnWall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7bc5d66d-6497-47de-84d8-9a64cd50c979"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveOnWall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""14225c8c-9863-4872-8118-2d88dfe0e695"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpOnWall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""976066ac-885f-496f-b0c6-43be02e50c56"",
                    ""path"": ""<Keyboard>/capsLock"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grapple"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""48b1d6a6-2486-43bc-a354-5441237a1bc5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveOnGrapple"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e704f133-7e42-498c-b339-17131827b280"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveOnGrapple"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3f619ab8-7eec-44b0-8769-5d6898ac0f28"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveOnGrapple"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ae115f69-fea3-49fd-9c4e-a501da608c91"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveOnGrapple"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""61f281d0-5faf-4654-a4ac-c9c4bc18815d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveOnGrapple"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0e06fe43-b4de-4fdd-b410-dbb72bba834d"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstSwordSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d31e0b05-d729-49f6-9f73-f1eaddcd9c01"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondSwordSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a23ae89b-ada2-45ee-88f8-1a562b08ab81"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NormalSwordSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""855203c8-f03d-4ea2-881b-6dfa63ac13ea"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwordBlock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4d8b325-96b3-4cd7-8186-1503a8852155"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThirdSwordSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CharacterControls
        m_CharacterControls = asset.FindActionMap("CharacterControls", throwIfNotFound: true);
        m_CharacterControls_Move = m_CharacterControls.FindAction("Move", throwIfNotFound: true);
        m_CharacterControls_Run = m_CharacterControls.FindAction("Run", throwIfNotFound: true);
        m_CharacterControls_Jump = m_CharacterControls.FindAction("Jump", throwIfNotFound: true);
        m_CharacterControls_Defense = m_CharacterControls.FindAction("Defense", throwIfNotFound: true);
        m_CharacterControls_MoveOnWall = m_CharacterControls.FindAction("MoveOnWall", throwIfNotFound: true);
        m_CharacterControls_JumpOnWall = m_CharacterControls.FindAction("JumpOnWall", throwIfNotFound: true);
        m_CharacterControls_Grapple = m_CharacterControls.FindAction("Grapple", throwIfNotFound: true);
        m_CharacterControls_MoveOnGrapple = m_CharacterControls.FindAction("MoveOnGrapple", throwIfNotFound: true);
        m_CharacterControls_FirstSwordSkill = m_CharacterControls.FindAction("FirstSwordSkill", throwIfNotFound: true);
        m_CharacterControls_SecondSwordSkill = m_CharacterControls.FindAction("SecondSwordSkill", throwIfNotFound: true);
        m_CharacterControls_NormalSwordSkill = m_CharacterControls.FindAction("NormalSwordSkill", throwIfNotFound: true);
        m_CharacterControls_ThirdSwordSkill = m_CharacterControls.FindAction("ThirdSwordSkill", throwIfNotFound: true);
        m_CharacterControls_SwordBlock = m_CharacterControls.FindAction("SwordBlock", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CharacterControls
    private readonly InputActionMap m_CharacterControls;
    private List<ICharacterControlsActions> m_CharacterControlsActionsCallbackInterfaces = new List<ICharacterControlsActions>();
    private readonly InputAction m_CharacterControls_Move;
    private readonly InputAction m_CharacterControls_Run;
    private readonly InputAction m_CharacterControls_Jump;
    private readonly InputAction m_CharacterControls_Defense;
    private readonly InputAction m_CharacterControls_MoveOnWall;
    private readonly InputAction m_CharacterControls_JumpOnWall;
    private readonly InputAction m_CharacterControls_Grapple;
    private readonly InputAction m_CharacterControls_MoveOnGrapple;
    private readonly InputAction m_CharacterControls_FirstSwordSkill;
    private readonly InputAction m_CharacterControls_SecondSwordSkill;
    private readonly InputAction m_CharacterControls_NormalSwordSkill;
    private readonly InputAction m_CharacterControls_ThirdSwordSkill;
    private readonly InputAction m_CharacterControls_SwordBlock;
    public struct CharacterControlsActions
    {
        private @PlayerInput m_Wrapper;
        public CharacterControlsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_CharacterControls_Move;
        public InputAction @Run => m_Wrapper.m_CharacterControls_Run;
        public InputAction @Jump => m_Wrapper.m_CharacterControls_Jump;
        public InputAction @Defense => m_Wrapper.m_CharacterControls_Defense;
        public InputAction @MoveOnWall => m_Wrapper.m_CharacterControls_MoveOnWall;
        public InputAction @JumpOnWall => m_Wrapper.m_CharacterControls_JumpOnWall;
        public InputAction @Grapple => m_Wrapper.m_CharacterControls_Grapple;
        public InputAction @MoveOnGrapple => m_Wrapper.m_CharacterControls_MoveOnGrapple;
        public InputAction @FirstSwordSkill => m_Wrapper.m_CharacterControls_FirstSwordSkill;
        public InputAction @SecondSwordSkill => m_Wrapper.m_CharacterControls_SecondSwordSkill;
        public InputAction @NormalSwordSkill => m_Wrapper.m_CharacterControls_NormalSwordSkill;
        public InputAction @ThirdSwordSkill => m_Wrapper.m_CharacterControls_ThirdSwordSkill;
        public InputAction @SwordBlock => m_Wrapper.m_CharacterControls_SwordBlock;
        public InputActionMap Get() { return m_Wrapper.m_CharacterControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterControlsActions set) { return set.Get(); }
        public void AddCallbacks(ICharacterControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_CharacterControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharacterControlsActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Defense.started += instance.OnDefense;
            @Defense.performed += instance.OnDefense;
            @Defense.canceled += instance.OnDefense;
            @MoveOnWall.started += instance.OnMoveOnWall;
            @MoveOnWall.performed += instance.OnMoveOnWall;
            @MoveOnWall.canceled += instance.OnMoveOnWall;
            @JumpOnWall.started += instance.OnJumpOnWall;
            @JumpOnWall.performed += instance.OnJumpOnWall;
            @JumpOnWall.canceled += instance.OnJumpOnWall;
            @Grapple.started += instance.OnGrapple;
            @Grapple.performed += instance.OnGrapple;
            @Grapple.canceled += instance.OnGrapple;
            @MoveOnGrapple.started += instance.OnMoveOnGrapple;
            @MoveOnGrapple.performed += instance.OnMoveOnGrapple;
            @MoveOnGrapple.canceled += instance.OnMoveOnGrapple;
            @FirstSwordSkill.started += instance.OnFirstSwordSkill;
            @FirstSwordSkill.performed += instance.OnFirstSwordSkill;
            @FirstSwordSkill.canceled += instance.OnFirstSwordSkill;
            @SecondSwordSkill.started += instance.OnSecondSwordSkill;
            @SecondSwordSkill.performed += instance.OnSecondSwordSkill;
            @SecondSwordSkill.canceled += instance.OnSecondSwordSkill;
            @NormalSwordSkill.started += instance.OnNormalSwordSkill;
            @NormalSwordSkill.performed += instance.OnNormalSwordSkill;
            @NormalSwordSkill.canceled += instance.OnNormalSwordSkill;
            @ThirdSwordSkill.started += instance.OnThirdSwordSkill;
            @ThirdSwordSkill.performed += instance.OnThirdSwordSkill;
            @ThirdSwordSkill.canceled += instance.OnThirdSwordSkill;
            @SwordBlock.started += instance.OnSwordBlock;
            @SwordBlock.performed += instance.OnSwordBlock;
            @SwordBlock.canceled += instance.OnSwordBlock;
        }

        private void UnregisterCallbacks(ICharacterControlsActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Defense.started -= instance.OnDefense;
            @Defense.performed -= instance.OnDefense;
            @Defense.canceled -= instance.OnDefense;
            @MoveOnWall.started -= instance.OnMoveOnWall;
            @MoveOnWall.performed -= instance.OnMoveOnWall;
            @MoveOnWall.canceled -= instance.OnMoveOnWall;
            @JumpOnWall.started -= instance.OnJumpOnWall;
            @JumpOnWall.performed -= instance.OnJumpOnWall;
            @JumpOnWall.canceled -= instance.OnJumpOnWall;
            @Grapple.started -= instance.OnGrapple;
            @Grapple.performed -= instance.OnGrapple;
            @Grapple.canceled -= instance.OnGrapple;
            @MoveOnGrapple.started -= instance.OnMoveOnGrapple;
            @MoveOnGrapple.performed -= instance.OnMoveOnGrapple;
            @MoveOnGrapple.canceled -= instance.OnMoveOnGrapple;
            @FirstSwordSkill.started -= instance.OnFirstSwordSkill;
            @FirstSwordSkill.performed -= instance.OnFirstSwordSkill;
            @FirstSwordSkill.canceled -= instance.OnFirstSwordSkill;
            @SecondSwordSkill.started -= instance.OnSecondSwordSkill;
            @SecondSwordSkill.performed -= instance.OnSecondSwordSkill;
            @SecondSwordSkill.canceled -= instance.OnSecondSwordSkill;
            @NormalSwordSkill.started -= instance.OnNormalSwordSkill;
            @NormalSwordSkill.performed -= instance.OnNormalSwordSkill;
            @NormalSwordSkill.canceled -= instance.OnNormalSwordSkill;
            @ThirdSwordSkill.started -= instance.OnThirdSwordSkill;
            @ThirdSwordSkill.performed -= instance.OnThirdSwordSkill;
            @ThirdSwordSkill.canceled -= instance.OnThirdSwordSkill;
            @SwordBlock.started -= instance.OnSwordBlock;
            @SwordBlock.performed -= instance.OnSwordBlock;
            @SwordBlock.canceled -= instance.OnSwordBlock;
        }

        public void RemoveCallbacks(ICharacterControlsActions instance)
        {
            if (m_Wrapper.m_CharacterControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICharacterControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_CharacterControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharacterControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CharacterControlsActions @CharacterControls => new CharacterControlsActions(this);
    public interface ICharacterControlsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnDefense(InputAction.CallbackContext context);
        void OnMoveOnWall(InputAction.CallbackContext context);
        void OnJumpOnWall(InputAction.CallbackContext context);
        void OnGrapple(InputAction.CallbackContext context);
        void OnMoveOnGrapple(InputAction.CallbackContext context);
        void OnFirstSwordSkill(InputAction.CallbackContext context);
        void OnSecondSwordSkill(InputAction.CallbackContext context);
        void OnNormalSwordSkill(InputAction.CallbackContext context);
        void OnThirdSwordSkill(InputAction.CallbackContext context);
        void OnSwordBlock(InputAction.CallbackContext context);
    }
}
